- id: validate-cff
  name: Validate CITATION.cff files
  description: Runs `cffconvert --validate` on `.cff` files.
  entry: cffconvert --validate -i
  language: python
  files: \.cff$
  types: [text]
  require_serial: true
