--- 
addons: 
  sonarcloud: 
    organization: citation-file-format
dist: trusty
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
python: 
  - "3.4"
  - "3.5"
  - "3.6"
script: 
  - "pytest test/"
  - "sonar-scanner -Dsonar.login=$SONAR_TOKEN -X"
sudo: false
