--- 
dist: xenial
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
sudo: false
python: 
  - "3.7"
  - "3.6"
  - "3.5"
  - "nightly"
env:
  - SCHEMA_VERSION=1.1.0
  - SCHEMA_VERSION=1.0.3
  - SCHEMA_VERSION=unsupported
script:
  - "bash test/test_consistent_file_naming.sh dir=test/"
  - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append test/$SCHEMA_VERSION/"
stages:
  - versioning
  - test
  - livetest
  - sonarcloud
jobs:
  include:
    - stage: versioning
      script: "python -m pytest test/test_consistent_versioning.py"
    - stage: livetest
      script:
        - "bash test/test_consistent_file_naming.sh dir=livetest/"
        - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append livetest/"
    - stage: sonarcloud
      script:
        - sonar-scanner
addons:
  sonarcloud:
    # using config from .sonarcloud.properties
    # see also: https://docs.travis-ci.com/user/sonarcloud/
