--- 
os: linux
dist: bionic
language: python
notifications: 
  email: 
    on_failure: change
    on_success: never
python: 
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements-dev.txt
env:
  - SCHEMA_VERSION=1.1.0
  - SCHEMA_VERSION=1.0.3
  - SCHEMA_VERSION=unsupported
script:
  - "bash test/test_consistent_file_naming.sh dir=test/"
  - "python3 -m pytest test/$SCHEMA_VERSION/"
stages:
  - versioning
  - test
  - livetest
  - sonarcloud
jobs:
  include:
    - stage: versioning
      script: "python3 -m pytest test/test_consistent_versioning.py"
    - stage: livetest
      env: ~
      script:
        - "bash test/test_consistent_file_naming.sh dir=livetest/"
        - "python3 -m pytest livetest/"
