--- 
dist: xenial
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
sudo: false
python: 
  - "3.7"
  - "3.6"
  - "3.5"
  - "nightly"
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements-dev.txt
env:
  - SCHEMA_VERSION=1.1.0
  - SCHEMA_VERSION=1.0.3
  - SCHEMA_VERSION=unsupported
script:
  - "bash test/test_consistent_file_naming.sh dir=test/"
  - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append test/$SCHEMA_VERSION/"
stages:
  - versioning
  - test
  - livetest
  - sonarcloud
jobs:
  include:
    - stage: versioning
      language: python
      script: "python3 -m pytest test/test_consistent_versioning.py"
    - stage: livetest
      language: python
      script:
        - "bash test/test_consistent_file_naming.sh dir=livetest/"
        - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append livetest/"
    - stage: sonarcloud
      language: java
      install:
      addons:
        sonarcloud:
          # see also: https://docs.travis-ci.com/user/sonarcloud/
          organization: citation-file-format
      env:
      script:
        - sonar-scanner -X -Dsonar.projectKey=citation-file-format_cff-converter-python -Dsonar.inclusions=cffconvert/**/*.py -Dsonar.test.inclusions=test/**/*.py,livetest/**/*.py
