--- 
before_script: 
  - "pip install -r requirements.txt"
dist: trusty
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
python: 
  - "3.5"
script: 
  - "pytest test/"
sudo: false

