--- 
dist: xenial
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
sudo: false
python: 
  - "3.7"
  - "3.6"
  - "3.5"
  - "nightly"
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements-dev.txt
env:
  - SCHEMA_VERSION=1.1.0
  - SCHEMA_VERSION=1.0.3
  - SCHEMA_VERSION=unsupported
script:
  - "bash test/test_consistent_file_naming.sh dir=test/"
  - "python3 -m pytest test/$SCHEMA_VERSION/"
stages:
  - versioning
  - test
  - livetest
  - sonarcloud
jobs:
  include:
    - stage: versioning
      script: "python3 -m pytest test/test_consistent_versioning.py"
    - stage: livetest
      env: ~
      script:
        - "bash test/test_consistent_file_naming.sh dir=livetest/"
        - "python3 -m pytest livetest/"
    - stage: sonarcloud
      addons:
        sonarcloud: ~
          # see also: https://docs.travis-ci.com/user/sonarcloud/
      env: ~
      script:
        - "python3 -m pytest --cov=cffconvert --cov-report=xml livetest/"
        - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append test/1.1.0/"
        - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append test/1.0.3/"
        - "python3 -m pytest --cov=cffconvert --cov-report=xml --cov-append test/unsupported/"
        - sonar-scanner -X -Dsonar.organization=citation-file-format
                           -Dsonar.projectKey=citation-file-format_cff-converter-python
                           -Dsonar.python.coverage.reportPaths=coverage.xml
                           -Dsonar.inclusions=cffconvert/**/*.py
                           -Dsonar.test.inclusions=test/**/*.py,livetest/**/*.py
