--- 
dist: xenial
language: python
notifications: 
  email: 
    on_failure: change
    on_succes: never
python: 
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: Tests for supported schema versions 
      env:
        - SCHEMA_VERSION=1.0.3
        - SCHEMA_VERSION=1.1.0
      script: 
        - "python -m pytest test/$SCHEMA_VERSION"
    - stage: Tests against live infrastructure
      script: 
        - "python -m pytest livetest"
sudo: false

# introduce a second stage later
  # 
  #   # also run the live tests, without test coverage calculation
  # - "pytest livetest/"
